version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gtri
      MYSQL_DATABASE: report-type-mapper
  web:
    build: .
    #from: node:4.0
    ports:
      - "1337:1337"
    volumes:
      - ./:/sails
    command: npm start
    depends_on:
      - db
    environment:
      - NODE_ENV=dev
